<?php
CoreUtils::getTemplateObject(
)->setTemplate(
  'table.twig'
)->addVariable(
  'tablescript',
  'myury.datatable.default'
)->addVariable(
  'title',
  'Quotes'
)->addVariable(
  'tabledata',
  ServiceAPI::setToDataSource(MyURY_Quote::getAll())
)->render();
?>
