#!/bin/sh
# Test edit.
# $FreeBSD$
#
# PROVIDE: myradio_daemon
# KEYWORD: shutdown
#
# This file enables the MyRadio Daemon to run as a service on a FreeBSD system.
# Modify paths as necessary and install in /usr/local/etc/rc.d/
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# myradio_daemon_enable (bool):	Set to NO by default.
#			Set it to YES to enable hawk.

. /etc/rc.subr

name=myradio_daemon
rcvar=myradio_daemon_enable

load_rc_config $name

: ${myradio_daemon_enable:="NO"}

command=/usr/local/www/myradio/src/Controllers/daemon.php
command_interpreter=/usr/local/bin/php
command_args="process >>/var/log/myradio/daemon.log 2>&1 &"
pidfile="/var/run/${name}.pid"

# Necessary for podcasts (ffmpeg)
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
run_rc_command "$1"
