#!/bin/sh

# $FreeBSD$
#
# PROVIDE: myradio_daemon
# KEYWORD: shutdown
#
# This file enables the MyRadio Daemon to run as a service on a FreeBSD system.
# Modify paths as necessary and install in /usr/local/etc/rc.d/
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# myradio_daemon_enable (bool):	Set to NO by default.
#			Set it to YES to enable hawk.

. /etc/rc.subr

name=myradio_daemon
rcvar=myradio_daemon_enable

load_rc_config myradio_daemon_enable

: ${myradio_daemon_enable:="NO"}

command=/usr/local/www/myradio/src/Controllers/daemon.php
command_interpreter=`which php`
command_args='process >/var/log/ury-org-uk/myradio_daemon.log 2>&1 &'
start_precmd=find_pidfile
stop_precmd=find_pidfile

find_pidfile()
{
	pidfile='/var/run/myradio_daemon.pid'
}

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
run_rc_command "$1"
