<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 00:53:46.
 */
class APCProviderTest extends PHPUnit_Framework_TestCase {

  /**
   * @var APCProvider
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = APCProvider::getInstance();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * Generated from @assert ('myury_core_test', 'test value', 0) == true.
   *
   * @covers APCProvider::set
   */
  public function testSet() {
    $this->assertEquals(
            true
            , $this->object->set('myury_core_test', 'test value', 0)
    );
  }

  /**
   * Generated from @assert ('myury_core_test') == 'test value'.
   *
   * @covers APCProvider::get
   */
  public function testGet() {
    $this->assertEquals(
            'test value'
            , $this->object->get('myury_core_test')
    );
  }

  /**
   * Generated from @assert ('myury_core_test') == true.
   *
   * @covers APCProvider::delete
   */
  public function testDelete() {
    $this->assertEquals(
            true
            , $this->object->delete('myury_core_test')
    );
  }

  /**
   * @covers APCProvider::purge
   * @todo   Implement testPurge().
   */
  public function testPurge() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers APCProvider::getInstance
   * @todo   Implement testGetInstance().
   */
  public function testGetInstance() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers APCProvider::__clone
   * @todo   Implement test__clone().
   */
  public function test__clone() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
