<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 01:02:13.
 */
class DatabaseTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Database
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = Database::getInstance();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * Generated from @assert ('SELECT * FROM public.tableethatreallydoesntexist') throws MyURYException.
   *
   * @covers Database::query
   * @expectedException MyURYException

   */
  public function testQuery() {
    $this->object->query('SELECT * FROM public.tableethatreallydoesntexist');
  }

  /**
   * Generated from @assert ('SELECT * FROM public.member') != false.
   *
   * @covers Database::query
   */
  public function testQuery2() {
    $this->assertNotEquals(
            false
            , $this->object->query('SELECT * FROM public.member')
    );
  }

  /**
   * @covers Database::num_rows
   * @todo   Implement testNum_rows().
   */
  public function testNum_rows() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::fetch_all
   * @todo   Implement testFetch_all().
   */
  public function testFetch_all() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::fetch_one
   * @todo   Implement testFetch_one().
   */
  public function testFetch_one() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::fetch_column
   * @todo   Implement testFetch_column().
   */
  public function testFetch_column() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::getInstance
   * @todo   Implement testGetInstance().
   */
  public function testGetInstance() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::__clone
   * @todo   Implement test__clone().
   */
  public function test__clone() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::decodeArray
   * @todo   Implement testDecodeArray().
   */
  public function testDecodeArray() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Database::intervalToTime
   * @todo   Implement testIntervalToTime().
   */
  public function testIntervalToTime() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
