ALTER TABLE myury.act_permission SET SCHEMA myradio;
ALTER TABLE myury.actions SET SCHEMA myradio;
ALTER TABLE myury.api_class_map SET SCHEMA myradio;
ALTER TABLE myury.api_key SET SCHEMA myradio;
ALTER TABLE myury.api_key_auth SET SCHEMA myradio;
ALTER TABLE myury.api_key_log SET SCHEMA myradio;
ALTER TABLE myury.api_method_auth SET SCHEMA myradio;
ALTER TABLE myury.award_categories SET SCHEMA myradio;
ALTER TABLE myury.award_member SET SCHEMA myradio;
ALTER TABLE myury.contract_versions SET SCHEMA myradio;
ALTER TABLE myury.error_rate SET SCHEMA myradio;
ALTER TABLE myury.menu_columns SET SCHEMA myradio;
ALTER TABLE myury.menu_links SET SCHEMA myradio;
ALTER TABLE myury.menu_module SET SCHEMA myradio;
ALTER TABLE myury.menu_sections SET SCHEMA myradio;
ALTER TABLE myury.menu_twigitems SET SCHEMA myradio;
ALTER TABLE myury.modules SET SCHEMA myradio;
ALTER TABLE myury.password_reset_token SET SCHEMA myradio;
ALTER TABLE myury.photos SET SCHEMA myradio;
ALTER TABLE myury.services SET SCHEMA myradio;
DROP TABLE myury.services_versions;
DROP TABLE myury.services_versions_member;
DROP SCHEMA myury;