name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build MyRadio and set up test environment
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml up -d
      - name: Run tests
        run: |
          docker compose exec myradio py.test
